//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCodeFluent.Identity
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Saturday, 19 November 2016 13:35.
    // Build:1.0.61214.0842
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0842")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    public partial class UserClaimCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<ModelCodeFluent.Identity.UserClaim>, System.Collections.Generic.ICollection<ModelCodeFluent.Identity.UserClaim>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<ModelCodeFluent.Identity.UserClaim> _baseList = new System.Collections.Generic.List<ModelCodeFluent.Identity.UserClaim>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<System.Guid, ModelCodeFluent.Identity.UserClaim> _baseTable = new System.Collections.Generic.Dictionary<System.Guid, ModelCodeFluent.Identity.UserClaim>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private ModelCodeFluent.Identity.User _claimsUserUser;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<ModelCodeFluent.Identity.UserClaim> _blm2033613734;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public UserClaimCollection()
        {
            this._blm2033613734 = new CodeFluent.Runtime.Utilities.BindingListManager<ModelCodeFluent.Identity.UserClaim>(this);
        }
        
        public UserClaimCollection(ModelCodeFluent.Identity.User claimsUserUser)
        {
            this._blm2033613734 = new CodeFluent.Runtime.Utilities.BindingListManager<ModelCodeFluent.Identity.UserClaim>(this);
            this._claimsUserUser = claimsUserUser;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<ModelCodeFluent.Identity.UserClaim> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<System.Guid, ModelCodeFluent.Identity.UserClaim> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ModelCodeFluent.Identity.User ClaimsUserUser
        {
            get
            {
                return this._claimsUserUser;
            }
        }
        
        public ModelCodeFluent.Identity.UserClaim this[int index]
        {
            get
            {
                return ((ModelCodeFluent.Identity.UserClaim)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((ModelCodeFluent.Identity.UserClaim)(value));
            }
        }
        
        public ModelCodeFluent.Identity.UserClaim this[System.Guid id]
        {
            get
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                ModelCodeFluent.Identity.UserClaim i = this.TryGetValue(id);
                return i;
            }
            set
            {
                if ((id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
                {
                    throw new System.ArgumentNullException("id");
                }
                if ((value == null))
                {
                    ModelCodeFluent.Identity.UserClaim userClaim = this.TryGetValue(id);
                    if ((userClaim != null))
                    {
                        this.Remove(userClaim);
                    }
                    return;
                }
                ModelCodeFluent.Identity.UserClaim existing = this.TryGetValue(value.Id);
                if ((existing != null))
                {
                    this.Remove(existing);
                }
                this.Add(value);
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm2033613734.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm2033613734.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm2033613734.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm2033613734.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm2033613734.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm2033613734.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm2033613734.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm2033613734.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(ModelCodeFluent.Identity.UserClaim item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(userClaim);
            return localAdd;
        }
        
        protected virtual int BaseAdd(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                throw new System.ArgumentNullException("userClaim");
            }
            if ((userClaim.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "userClaim", "ModelCodeFluent.Identity.UserClaim");
            }
            try
            {
                this.BaseTable.Add(userClaim.Id, userClaim);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(ModelCodeFluent.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "ModelCodeFluent.Identity.UserClaimCollection", userClaim.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(ModelCodeFluent.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "ModelCodeFluent.Identity.UserClaimCollection", userClaim.Id), ae);
            }
            userClaim.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            if ((this._claimsUserUser != null))
            {
                userClaim.User = this._claimsUserUser;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(userClaim);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, userClaim, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            ModelCodeFluent.Identity.UserClaim userClaim = null;
            try
            {
                userClaim = ((ModelCodeFluent.Identity.UserClaim)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((userClaim == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(userClaim);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<ModelCodeFluent.Identity.UserClaim>.Add(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            this.BaseAdd(userClaim);
        }
        
        public virtual ModelCodeFluent.Identity.UserClaim AddByEntityKey(string key)
        {
            ModelCodeFluent.Identity.UserClaim userClaim = ModelCodeFluent.Identity.UserClaim.LoadByEntityKey(key);
            if (((userClaim != null) 
                        && (this.Contains(userClaim) == false)))
            {
                this.Add(userClaim);
            }
            return userClaim;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<ModelCodeFluent.Identity.UserClaim> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(ModelCodeFluent.Identity.UserClaim[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(ModelCodeFluent.Identity.UserClaim[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            bool localContains = this.BaseContains(userClaim);
            return localContains;
        }
        
        protected virtual bool BaseContains(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(userClaim.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            ModelCodeFluent.Identity.UserClaim userClaim;
			userClaim = value as ModelCodeFluent.Identity.UserClaim;
            return this.Contains(userClaim);
        }
        
        public int IndexOf(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            int localIndexOf = this.BaseIndexOf(userClaim);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(userClaim);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            ModelCodeFluent.Identity.UserClaim userClaim;
			userClaim = value as ModelCodeFluent.Identity.UserClaim;
            return this.IndexOf(userClaim);
        }
        
        public void Insert(int index, ModelCodeFluent.Identity.UserClaim userClaim)
        {
            this.BaseInsert(index, userClaim);
        }
        
        protected virtual void BaseInsert(int index, ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                throw new System.ArgumentNullException("userClaim");
            }
            try
            {
                this.BaseTable.Add(userClaim.Id, userClaim);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(ModelCodeFluent.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "ModelCodeFluent.Identity.UserClaimCollection", userClaim.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(ModelCodeFluent.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "ModelCodeFluent.Identity.UserClaimCollection", userClaim.Id), ae);
            }
            this.BaseList.Insert(index, userClaim);
            if ((this._claimsUserUser != null))
            {
                userClaim.User = this._claimsUserUser;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, userClaim, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            ModelCodeFluent.Identity.UserClaim userClaim;
			userClaim = value as ModelCodeFluent.Identity.UserClaim;
            this.Insert(index, userClaim);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                ModelCodeFluent.Identity.UserClaim UserClaim = this[0];
                this.BaseRemove(UserClaim);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            return this.BaseRemove(userClaim);
        }
        
        protected virtual bool BaseRemove(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                throw new System.ArgumentNullException("userClaim");
            }
            int index = this.IndexOf(userClaim);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<ModelCodeFluent.Identity.UserClaim>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(userClaim);
            userClaim.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(userClaim.Id);
            if ((this._claimsUserUser != null))
            {
                userClaim.User = null;
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, userClaim, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            ModelCodeFluent.Identity.UserClaim userClaim;
			userClaim = value as ModelCodeFluent.Identity.UserClaim;
            this.Remove(userClaim);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<ModelCodeFluent.Identity.UserClaim>.ListChangedTypeDeleting)), index));
            ModelCodeFluent.Identity.UserClaim userClaim = this.BaseList[index];
            if ((userClaim != null))
            {
                userClaim.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(userClaim.Id);
            }
            if ((this._claimsUserUser != null))
            {
                userClaim.User = null;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, userClaim, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<ModelCodeFluent.Identity.UserClaim> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<ModelCodeFluent.Identity.UserClaim> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private ModelCodeFluent.Identity.UserClaim TryGetValue(System.Guid key)
        {
            ModelCodeFluent.Identity.UserClaim userClaim;
            if ((this.BaseTable.TryGetValue(key, out userClaim) == true))
            {
                return userClaim;
            }
            return null;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                ModelCodeFluent.Identity.UserClaim userClaim = this[index];
                userClaim.Save();
                if ((userClaim.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(userClaim);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._claimsUserUser = null;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    ModelCodeFluent.Identity.UserClaim userClaim = new ModelCodeFluent.Identity.UserClaim();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(userClaim)).ReadRecord(reader);
                    if ((this.BaseContains(userClaim) == false))
                    {
                        this.BaseAdd(userClaim);
                        count = (count + 1);
                    }
                    userClaim.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ModelCodeFluent.Identity.UserClaimCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            ModelCodeFluent.Identity.UserClaimCollection ret = new ModelCodeFluent.Identity.UserClaimCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = ModelCodeFluent.Identity.UserClaimCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(ModelCodeFluent.Constants.ModelCodeFluentStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ModelCodeFluent.Identity.UserClaimCollection LoadAll()
        {
            ModelCodeFluent.Identity.UserClaimCollection ret = ModelCodeFluent.Identity.UserClaimCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(ModelCodeFluent.Constants.ModelCodeFluentStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "UserClaim", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(ModelCodeFluent.Constants.ModelCodeFluentStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = ModelCodeFluent.Identity.UserClaimCollection.PageDataLoadAll(null);
            return reader;
        }
        
        private void LoadByUser(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, ModelCodeFluent.Identity.User user)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState userState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((user != null))
            {
                userState = user.EntityState;
            }
            this._claimsUserUser = user;
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    ModelCodeFluent.Identity.UserClaim userClaim = new ModelCodeFluent.Identity.UserClaim();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(userClaim)).ReadRecord(reader);
                    if ((this.BaseContains(userClaim) == false))
                    {
                        this.BaseAdd(userClaim);
                        count = (count + 1);
                    }
                    userClaim.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((user != null))
            {
                user.EntityState = userState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ModelCodeFluent.Identity.UserClaimCollection PageLoadByUser(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, ModelCodeFluent.Identity.User user)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            ModelCodeFluent.Identity.UserClaimCollection ret = new ModelCodeFluent.Identity.UserClaimCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = ModelCodeFluent.Identity.UserClaimCollection.PageDataLoadByUser(pageOptions, user);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByUser(pageIndex, pageSize, pageOptions, reader, user);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(ModelCodeFluent.Constants.ModelCodeFluentStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ModelCodeFluent.Identity.UserClaimCollection LoadByUser(ModelCodeFluent.Identity.User user)
        {
            ModelCodeFluent.Identity.UserClaimCollection ret = ModelCodeFluent.Identity.UserClaimCollection.PageLoadByUser(int.MinValue, int.MaxValue, null, user);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByUser(CodeFluent.Runtime.PageOptions pageOptions, ModelCodeFluent.Identity.User user)
        {
            if ((user == null))
            {
                return null;
            }
            if ((user.Id.Equals(CodeFluentPersistence.DefaultGuidValue) == true))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "user", "ModelCodeFluent.Identity.User");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(ModelCodeFluent.Constants.ModelCodeFluentStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "UserClaim", "LoadByUser");
            persistence.AddParameter("@UserId", user.Id, CodeFluentPersistence.DefaultGuidValue);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(ModelCodeFluent.Constants.ModelCodeFluentStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByUser(ModelCodeFluent.Identity.User user)
        {
            System.Data.IDataReader reader = ModelCodeFluent.Identity.UserClaimCollection.PageDataLoadByUser(null, user);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(ModelCodeFluent.Identity.UserClaimCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(ModelCodeFluent.Identity.UserClaim)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<ModelCodeFluent.Identity.UserClaim> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((ModelCodeFluent.Identity.UserClaim)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual ModelCodeFluent.Identity.UserClaimCollection Clone(bool deep)
        {
            ModelCodeFluent.Identity.UserClaimCollection ret = new ModelCodeFluent.Identity.UserClaimCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm2033613734.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            ModelCodeFluent.Identity.UserClaim add = new ModelCodeFluent.Identity.UserClaim();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((ModelCodeFluent.Identity.UserClaim)(e.NewObject));
            if ((add == null))
            {
                add = new ModelCodeFluent.Identity.UserClaim();
            }
            add.Id = System.Guid.NewGuid();
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm2033613734.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm2033613734.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm2033613734.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm2033613734.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<ModelCodeFluent.Identity.UserClaim> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<System.Guid> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            ModelCodeFluent.Identity.UserClaim existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<System.Guid>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<System.Guid> item = ((CodeFluent.Runtime.Utilities.IKeyable<System.Guid>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(ModelCodeFluent.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "ModelCodeFluent.Identity.UserClaimCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(ModelCodeFluent.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "ModelCodeFluent.Identity.UserClaimCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ModelCodeFluent.Identity.UserClaimCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return ModelCodeFluent.Identity.UserClaimCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ModelCodeFluent.Identity.UserClaimCollection PageLoadByUser(int pageIndex, int pageSize, System.Guid userId)
        {
            ModelCodeFluent.Identity.User user = ModelCodeFluent.Identity.User.Load(userId);
            if ((user == null))
            {
                return new ModelCodeFluent.Identity.UserClaimCollection();
            }
            return ModelCodeFluent.Identity.UserClaimCollection.PageLoadByUser(pageIndex, pageSize, null, user);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                return false;
            }
            bool ret = userClaim.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            bool ret = ModelCodeFluent.Identity.UserClaim.Save(userClaim);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(ModelCodeFluent.Identity.UserClaim userClaim)
        {
            if ((userClaim == null))
            {
                return false;
            }
            bool ret = userClaim.Delete();
            return ret;
        }
    }
}
